[Machine]
cpu_load = 100
cpu_cores = 1
memory_load = 1000000000

[Links]
channels = ["topic"]

[Links.topic]
load_bps = 10000000

[DUST]
application_name = "ETS-message-block"
config_file = "configuration.json"
module_dir = "modules"

[output_files]
json_output_file_path = "/Users/vincentcharpentier/School/Master/MAP/Decoder/CAMv1.json"