
[DUST]
application_name = "ETS-message-block"
config_file = "configuration.json"
module_dir = "modules"

[output_files]
json_output_file_path = "/Users/vincentcharpentier/School/Master/MAP/Decoder/cam.json"

[usage]
cam_decoder = "false"
cam_generator = "true"
special_vehicle_service = "true"

[GPS]
GPS_enabled = "false"
GPS_host_ip = "143.129.82.170"
GPS_port = 2947